console.log("Hi there! My first JavaScript code!")
console.log(document.querySelector('.greeting'))
let greetingDiv = document.querySelector ('.greeting')
greetingDiv.textContent = 'Welcome to my page! This message was generated by my JavaScript code!'